# Generated by Django 5.1.4 on 2025-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_otp_email_otp_expires_at_otp_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
        ),
    ]
